export const ERROR_TYPE = {
    ZOD_ERROR: 'ZOD_ERROR',
    NOT_FOUND_ERROR: 'NOT_FOUND_ERROR',
    VALIDATION_ERROR: 'VALIDATION_ERROR',
    AUTH_ERROR: 'AUTH_ERROR',
    AUTHORIZATION_ERROR: 'AUTHORIZATION_ERROR',
    INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
    CONFLICT_ERROR: 'CONFLICT_ERROR',
};
